language: python

python:
  - 3.6

bundler_args: --retry 3

install:
  - sudo apt-get update
  - ./_travis_utils/travis_miniconda.sh
  - PATH="$HOME/miniconda/bin:$PATH"
  - conda env create -f environment.yml
  - source activate grmpy-semipar

script:
  - travis_wait python _travis_utils/travis_runner.py
